### ISSUE TITLE
[Vue warn]: Error in render: "TypeError: e.extend is not a function"

### ISSUE THREAD

**Issue by tracejijo** [phoenixwong/vue-timepicker#10]
while trying to follow the installation steps, the error occurred `[Vue warn]: Error in render: "TypeError: e.extend is not a function ` while trying to add the given line in vue.

`  components: {VueTimepicker},
`
if its not given this line , the drop down works but its blank, no values are there

**Comment by charrismatic** [comment]
I've tried this every way I could think of and still the the same error.  
(I've tried: `/dist/...min.js` | `/dist/...js` | and used `unpkg.com` cdn to load it.)

**Comment by phoenixwong** [comment]
Sorry for the late reply. Please use [vue2-timepicker](https://github.com/phoenixwong/vue2-timepicker), which is the Vue 2.x version of this repository and with all the latest fixes.
