### ISSUE TITLE
document writes :time-value to complete data bind, but actually is value.sync

### ISSUE THREAD

**Issue by FinnWu** [phoenixwong/vue-timepicker#12]
document writes :time-value to complete data bind, but actually is value.sync,hope writer can modify.

**Comment by phoenixwong** [comment]
This Vue 1.x component will NOT be updated again. Please go for [vue2-timepicker](https://github.com/phoenixwong/vue2-timepicker), which is the Vue 2.x version of this repository.

[More notice here](https://github.com/phoenixwong/vue-timepicker#notice)
