### ISSUE TITLE
How to add name field on the field

### ISSUE THREAD

**Issue by sonnny** [phoenixwong/vue-timepicker#3]
How do I add a name property to the timepicker use to post when submitting the form?

Thanks,
Sonny

**Comment by phoenixwong** [comment]
Hi @sonnny ,

Sorry for the late reply. Can you provide some demo code of the form you've been working with? Thanks!

**Comment by phoenixwong** [comment]
Please feel free to reopen this ticket with some sample codes provided. Thanks :)

**Comment by psychonetic** [comment]
Can you please add a name property to the time field to add support for vue-validate and other validation tools?

    <vue-timepicker name="time" v-validate data-vv-rules="required"></vue-timepicker>

Otherwise vue-validate can't validate the field.
