### ISSUE TITLE
Cannot find module "!!babel-loader!

### ISSUE THREAD

**Issue by lukpep** [phoenixwong/vue-timepicker#4]
Vue 1.0.28
time-picker installed via npm:
`npm install vue-time-picker --save-dev`

in my single file omponent (*.vue file) I import it:
`import VueTimepicker from 'vue-time-picker'`

And I receive:

> build.js:41948 Uncaught Error: Cannot find module "!!babel-loader!./../../vue-loader/lib/selector.js?type=script&index=0!./vue-timepicker.vue"

**Comment by phoenixwong** [comment]
It's possible that a relative path is used somewhere in your webpack config, but an absolute path is expected here.

Can you try adding the following lines in your configuration?

```
resolveLoader: {
  root: path.join(__dirname, 'node_modules')
}
```

Ref [webpack docs](https://webpack.github.io/docs/configuration.html#module-loaders)

**Comment by phoenixwong** [comment]
Hi @lukpep ,

Hope the configuration from the previous comment resolve the issue you met. Plus, you can also try uninstall

```
npm uninstall vue-time-picker
```

Then re-install again through

```
npm install vue-time-picker --save
```

Please feel free to reopen this ticket if the issue still exists.
