### ISSUE TITLE
change event won't return all predefined format

### ISSUE THREAD

**Issue by alexlauzon** [phoenixwong/vue-timepicker#5]
The docs says: With `time-value` set, change event will only returns values in predefined format but it doesn't seem to return all of them.

If I use hh:mm A as a format, I get the hh and mm data but not the A. It's not set. If I remove the value for :time-value.sync, then I receive all the data. Would it be possible to return the A when it is chosen in the format?

I'm using Vue 1.x version

**Comment by phoenixwong** [comment]
Hi @alexlauzon ,

Please include the `A` token in the `.sync` variable. For example:

``` html
<!-- HTML -->
<vue-timepicker format="hh:mm A" :time-value.sync="demoData" @change="changeHandler"></vue-timepicker>
```

``` javascript
// JS
data () {
  return {
    demoData: {hh: '', mm: '', A: ''}  // Make sure `A` token is included in the sync data, even an empty string will do
  }
},

methods: {
  changeHandler (eventData) {
    console.log(eventData) // outputs -> {data: {hh:..., mm:..., A:... }}
  }
}
```

**Comment by alexlauzon** [comment]
It works.

Thanks for the quick answer!
