### ISSUE TITLE
Selector doesn't overlap parent element

### ISSUE THREAD

**Issue by baristaGeek** [phoenixwong/vue-timepicker#9]
![screen shot 2018-06-27 at 11 32 17 am](https://user-images.githubusercontent.com/8325094/41987082-ce19bd9e-79fd-11e8-8753-e4d010fa54f8.png)

**Comment by phoenixwong** [comment]
Sorry for the late reply. This Vue 1.x component will NOT be updated again. Please go for [vue2-timepicker](https://github.com/phoenixwong/vue2-timepicker), which is the Vue 2.x version of this repository.
